### ISSUE TITLE
Test for Java irrelevant

### ISSUE THREAD

**Issue by IRus** [JuliaLang/Microbenchmarks#33]
Consider use of [JMH](http://openjdk.java.net/projects/code-tools/jmh/) for java performance tests. Also, use latest stable JVM for tests.

see https://github.com/JuliaLang/julia/issues/19460
proposed PR for main repo (which was ignored): https://github.com/JuliaLang/julia/pull/20984

**Comment by acxz** [comment]
> Consider use of [JMH](http://openjdk.java.net/projects/code-tools/jmh/) for java performance tests.

Quoting @StefanKarpinski 's [comment](https://github.com/JuliaLang/julia/issues/19460#issuecomment-264188804) here:

> Absent evidence that what we're timing is actually wrong, we're not going to make that change ourselves. Of course, if you want to submit a PR that changes the benchmark code to use JMH, that would be welcomed (assuming we can get it to compile and run without too much trouble).

I know you must have put in some good effort in making the benchmarks more idiomatic for java in your previous PR, however, we are trying to keep things a bit simple this repo, especially since this repo is essentially in maintenance mode.  Again feel free to rewrite your PR to use JMH for this repo, but there honestly is not much merit in doing so and a strong chance that we won't accept it (or just let it sit). If you would to like see thorough and more complete benchmarks I suggest you to take a look at [benchmarkgames](https://salsa.debian.org/benchmarksgame-team/benchmarksgame).

> Also, use latest stable JVM for tests.

This has been accomplished with the lastest changes to this repo's CI.

If you still have other concerns feel free to comment! Closing for now though.
